
if Exists(Select 1 from sys.procedures where name='USP_INSERT_ERRORLOG')
Begin	
	Drop Procedure USP_INSERT_ERRORLOG
End
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_INSERT_ERRORLOG]
	@FORM_NAME		VARCHAR(200),
	@CUSTOM_MSG		VARCHAR(1000),
	@ERROR_MSG		VARCHAR(2000),
	@STACK_TRACE	VARCHAR(MAX),
	@IP_ADDRESS		VARCHAR(100)
AS
BEGIN

	INSERT INTO  dbo.ERROR_LOG (FORM_NAME,CUSTOM_MSG ,ERROR_MSG ,STACK_TRACE,LOG_TIME,IP_ADDRESS )
	VALUES (@FORM_NAME,@CUSTOM_MSG ,@ERROR_MSG ,@STACK_TRACE, dbo.fnGetDate(),@IP_ADDRESS)

END
GO
